General:
    comment:
    seed: 2023
    fp16: False
    amp_level: O2
    precision: 32
    multi_gpu_mode: dp
    gpus: [0]
    epochs: &epoch 200
    grad_acc: 20
    frozen_bn: False
    patience: 20
    server: train #train #test
    log_path: log/

Data:
    dataset_name: covid_data
    data_shuffle: False
    data_dir: /jhcnas2/home/yipkc/COVID-19_Radiography_Dataset/
    fold: 1
    nfold: 4

    train_dataloader:
        batch_size: 1
        num_workers: 8

    test_dataloader:
        batch_size: 1
        num_workers: 8

Model:
    name: ResNet50
    n_classes: 4


Optimizer:
    opt: adam
    lr: 0.001
    opt_eps: null
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss

